### ISSUE TITLE
fake release, doesn't match with the original version

### ISSUE THREAD

**Issue by aleeeh07** [stussbanji/HAM-Valorant-Spoofer#1]
this is barely the mid ham code

**Comment by stussbanji** [comment]
you must be retarded, because this is the assets not the code you fuckin moron. I grabbed this shit straight from the spoofing process. don't come crying to me now.

**Comment by aleeeh07** [comment]
💀 there are many other things in memory kiddo

**Comment by stussbanji** [comment]
same person that tells their customers to use TMAC and stolen cleaner lmao
